micronaut:
  application:
    name: msAccountMicronaut
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    url: jdbc:mysql://localhost:3306/example
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    schema-generate: CREATE_DROP
    dialect: MYSQLDialect

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
